# Generated by Django 4.1 on 2024-03-07 16:13

from django.db import migrations, models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(default=None, max_length=10)),
                ('name', models.CharField(default=None, max_length=100)),
                ('country', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('location', models.CharField(default=None, max_length=255)),
                ('postcode', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(default=None, max_length=50)),
                ('star', models.IntegerField(default=3)),
                ('description', models.TextField(default=None)),
                ('facility', models.TextField(default=None)),
                ('image', models.ImageField(default=None, upload_to='hotel_image')),
                ('hotel_id', models.CharField(default=None, max_length=10)),
                ('name', models.CharField(default=None, max_length=100)),
                ('country', models.CharField(default=None, max_length=50)),
                ('city', models.CharField(default=None, max_length=50)),
                ('location', models.CharField(default=None, max_length=255)),
                ('postcode', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(default=None, max_length=50)),
                ('star', models.IntegerField(default=3)),
                ('description', models.TextField(default=None)),
                ('facility', models.TextField(default=None)),
                ('image', models.ImageField(default=None, upload_to='hotel_image')),
            ],
        ),
        migrations.CreateModel(
            name='hotelmanager',
            name='hotelmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_id', models.CharField(default=None, max_length=10)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(default='+0000000000', max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('manage_id', models.CharField(default=None, max_length=10)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(default='+0000000000', max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=None, max_length=10)),
                ('username', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('user_id', models.CharField(default=None, max_length=10)),
                ('username', models.CharField(default=None, max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(default='+0000000000', max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='roomtype',
            name='roomtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=12)),
                ('guests', models.IntegerField(default=2)),
                ('facility', models.TextField(default=None)),
                ('image', models.ImageField(default=None, upload_to='room_image')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyStay.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_number', models.CharField(default=None, max_length=10)),
                ('Room_number', models.CharField(default=None, max_length=10)),
                ('availability', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyStay.roomtype')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyStay.hotelmanager'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyStay.hotelmanager'),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_num', models.CharField(default=None, max_length=50)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_date', models.DateField(default=None)),
                ('to_date', models.DateField(default=None)),
                ('ref_num', models.CharField(default=None, max_length=50)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_date', models.DateField(default=None)),
                ('to_date', models.DateField(default=None)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('reserved_name', models.CharField(default=None, max_length=50)),
                ('reserved_phone', models.CharField(default=None, max_length=50)),
                ('status', models.IntegerField(default='1')),
                ('check_in_date', models.DateTimeField(blank=True, null=True)),
                ('check_out_date', models.DateTimeField(blank=True, null=True)),
                ('review_star', models.IntegerField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('reply_date', models.DateTimeField(blank=True, null=True)),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyStay.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyStay.user')),
            ],
        ),
    ]
