# Generated by Django 5.0.2 on 2024-02-22 10:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotelmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(default='default_hotel_name', max_length=50)),
                ('manage_id', models.CharField(default='default_manage_id', max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(default='+0000000000', max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('position', models.CharField(default='Manager', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='roomtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Standard', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=100.0, max_digits=12)),
                ('facility', models.TextField(default='Basic room facilities.')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='default_user_id', max_length=10)),
                ('username', models.CharField(default='default_username', max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(default='+0000000000', max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(default='default_hotel_id', max_length=10)),
                ('name', models.CharField(default='default_hotel_name', max_length=100)),
                ('city', models.CharField(default='default_city', max_length=50)),
                ('location', models.CharField(default='default_location', max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(default='+0000000000', max_length=50)),
                ('star', models.IntegerField(default=3)),
                ('description', models.TextField(default='No description provided.')),
                ('facility', models.TextField(default='Basic facilities.')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyStay.hotelmanager')),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='001', max_length=10)),
                ('availability', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyStay.hotel')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyStay.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_num', models.CharField(default='REF0001', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_in_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('status', models.TextField(default='1')),
                ('review_star', models.IntegerField(default=5)),
                ('review_comment', models.TextField(default='No comment.')),
                ('review_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyStay.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EasyStay.user')),
            ],
        ),
    ]
