# Generated by Django 4.1 on 2024-03-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
