# Generated by Django 4.1 on 2024-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='guests',
            field=models.IntegerField(default=2),
        ),
    ]
