# Generated by Django 5.0.2 on 2024-03-02 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("EasyStay", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="date",
            new_name="booking_date",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="number",
            new_name="Room_number",
        ),
        migrations.RemoveField(
            model_name="hotelmanager",
            name="position",
        ),
        migrations.RemoveField(
            model_name="room",
            name="hotel",
        ),
        migrations.AddField(
            model_name="booking",
            name="from_date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="booking",
            name="reserved_name",
            field=models.CharField(default="Name", max_length=50),
        ),
        migrations.AddField(
            model_name="booking",
            name="reserved_phone",
            field=models.CharField(default="Phone", max_length=50),
        ),
        migrations.AddField(
            model_name="booking",
            name="to_date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="hotel",
            name="image",
            field=models.ImageField(default=None, upload_to="hotel_image"),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="hotel",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="EasyStay.hotel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roomtype",
            name="image",
            field=models.ImageField(default=None, upload_to="room_image"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_in_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="review_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="review_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="review_star",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.IntegerField(default="1"),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="city",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="hotel_id",
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name="hotelmanager",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="hotelmanager",
            name="hotel_name",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name="hotelmanager",
            name="manage_id",
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="type",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default=None, max_length=50),
        ),
    ]
