# Generated by Django 4.1 on 2024-03-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0002_roomtype_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
