# Generated by Django 5.0.2 on 2024-02-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0003_rename_name_booking_reserved_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='images_default.jpg', upload_to='hotel_image'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(default='images_default.jpg', upload_to='room_image'),
        ),
    ]
