# Generated by Django 4.1 on 2024-03-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0004_alter_hotel_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.CharField(blank=True, default='Great Britain', max_length=50),
        ),
    ]
