# Generated by Django 5.0.2 on 2024-02-25 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0004_hotel_image_roomtype_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='booking_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reserved_phone',
            field=models.CharField(default='Phone', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='review_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='review_star',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='city',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default=None, upload_to='hotel_image'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='hotelmanager',
            name='hotel_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelmanager',
            name='manage_id',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='image',
            field=models.ImageField(default=None, upload_to='room_image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
