# Generated by Django 5.0.2 on 2024-02-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0006_rename_number_room_room_number_remove_room_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='from_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(default='1'),
        ),
    ]
