# Generated by Django 5.0.2 on 2024-02-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0007_booking_from_date_booking_to_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='from_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_date',
            field=models.DateField(default=None),
        ),
    ]
