# Generated by Django 5.0.2 on 2024-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0008_alter_booking_from_date_alter_booking_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='review_comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='review_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='review_star',
            field=models.IntegerField(null=True),
        ),
    ]
