# Generated by Django 5.0.2 on 2024-03-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0011_alter_roomtype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='postcode',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='location',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
