# Generated by Django 5.0.2 on 2024-03-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0012_hotel_country_hotel_postcode_alter_hotel_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='guest_number',
            field=models.IntegerField(default=2),
        ),
    ]
