# Generated by Django 5.0.2 on 2024-03-02 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0014_rename_guest_number_roomtype_guests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='country',
        ),
    ]
