# Generated by Django 5.0.2 on 2024-03-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0015_remove_hotel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default='Great Britain', max_length=50),
        ),
    ]
