# Generated by Django 5.0.2 on 2024-03-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0017_alter_hotel_country_alter_hotel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ref_num',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reserved_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reserved_phone',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='Room_number',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='facility',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=12),
        ),
    ]
