# Generated by Django 5.0.2 on 2024-03-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0019_remove_hotelmanager_hotel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='star',
            field=models.FloatField(default=3),
        ),
    ]
