# Generated by Django 5.0.2 on 2024-03-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyStay', '0020_alter_hotel_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='star',
            field=models.IntegerField(default=3),
        ),
    ]
